Test configuration and update scraper
Super-Fast-Buyers/auctions-scraper pull request #3
Opened 2024-04-23 08:13 UTC by kaminyv

Configuration testing has been performed and the scraper has been updated for efﬁcient data acquisition.

2024-04-26 15:16 UTC, Lekki369 commented on auctionscraper/scraper.py
> +def page_request(page: Page, url: str, selector: str, timeout: int) \
Where is this used?

2024-04-27 04:15 UTC, kaminyv commented on auctionscraper/scraper.py
> +def page_request(page: Page, url: str, selector: str, timeout: int) \
Look at line 102

2024-04-27 23:15 UTC, Lekki369 commented on auctionscraper/scraper.py
> +def page_request(page: Page, url: str, selector: str, timeout: int) \
ok

2024-04-27 23:17 UTC, Lekki369 approved these changes

2024-04-29 07:18 UTC, Lekki369 commented
@kaminyv  fix your merge conflicts

2024-04-29 07:19 UTC, Lekki369 requested changes
FIX YOUR MERGE CONFLICTS

2024-04-29 07:51 UTC, kaminyv commented
@Lekki369 I do not have permission to resolve these conflicts.

2024-05-01 12:47 UTC, kaminyv commented
@Lekki369 

1. Yes, these changes are in addition to the work done.
2. You can finish this code review, conflicts shouldn't bother us anymore.

2024-05-03 06:43 UTC, Lekki369 reviewed
ok, i will go through it

2024-05-03 07:15 UTC, Lekki369 reviewed
I Commented out this!!!!

2025-04-20 14:42 UTC, merged